### ISSUE TITLE
Connection handling

### ISSUE THREAD

**Issue by lucacorti** [lucacorti/lapin#11]
Currently connection establishment is synchronous and badly handled. If a broker is unavailable the startup process just hangs.

Possibly investigate the use of the Connection library to implement a robust async connection with backoff mechanism.

**Comment by lswith** [comment]
The hanging is even more annoying than usual because its hard to debug. It prevents the app from starting so that the logger doesn't always get booted up while waiting for the connection to connect.

I think the best bet is simply to die if a broker is unavailable during startup.

**Comment by lucacorti** [comment]
Yes, connection handling is the next issue I'm going to address as soon as possible.
