### ISSUE TITLE
The typespecs of some callbacks of `Lapin.Connection` may be improper

### ISSUE THREAD

**Issue by junjielu-tubi** [lucacorti/lapin#151]
For example, the callback `handle_deliver` is specified as the following:

```elixir
@callback handle_deliver(Channel.t(), Message.t()) :: on_deliver
```

But if we look at the code where it is invoked:

https://github.com/lucacorti/lapin/blob/9b7d69aa1ea7149ead007c8cf55a5ae23fbdd6bb/lib/lapin/connection.ex#L315-L329

We will find that its first parameter should be a `Lapin.Consumer.t()`.

I guess that all types of the `Lapin.Connection` callback parameters that are now `AMQP.Channel.t()` need to be corrected.

**Comment by lucacorti** [comment]
hi @junjielu-tubi,

Looks like you are right, a new release is out with updates and fixed typespecs.

Thanks for the report!

Luca
