### ISSUE TITLE
Gracefully shutdown connection on connection.close

### ISSUE THREAD

**Issue by vermaxik** [lucacorti/lapin#167]
👋  Thank you for great library, it's very easy to use. 

With a time we started getting the `connection.close` exception. It restores the connection very quickly, but it spams Sentry with exceptions. 

Is it possible to handle this and log the errors more gracefully?

```elixir
GenServer MyApp.Workers.Lapin.AMQPConsumerWorker terminating
** (stop) exited in: :gen_server.call(#PID<0.4984.0>, {:command, {:close, {:"connection.close", 200, "Goodbye", 0, 0}, 70000}}, 70000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib 5.2.2) gen_server.erl:419: :gen_server.call/3
    (amqp 3.3.0) lib/amqp/connection.ex:258: AMQP.Connection.close/1
    (stdlib 5.2.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1575501252.1150025729.99474>, :process, #PID<0.4984.0>, :socket_closed_unexpectedly}
```
mix.lock
```bash
lapin: 1.0.6
amqp: 3.3.0
amqp_client: 3.12.13
```

Thank you.

**Comment by lucacorti** [comment]
Hi, thanks for the report.

I'm not sure why there's a trap_exit in the connection process. I think it may be it. Can you try #168 and see if it fixes this?

**Comment by vermaxik** [comment]
> Hi, thanks for the report.
> 
> I'm not sure why there's a trap_exit in the connection process. I think it may be it. Can you try #168 and see if it fixes this?

Thank you @lucacorti for quick response.

Tried with `{:lapin, git: "https://github.com/lucacorti/lapin", branch: "no_trap_exit"}` and have the same exit error

```
GenServer MyApp.Workers.Lapin.AMQPPublisherWorker terminating
** (stop) exited in: :gen_server.call(#PID<0.5048.0>, {:command, {:close, {:"connection.close", 200, "Goodbye", 0, 0}, 70000}}, 70000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib 5.2.2) gen_server.erl:419: :gen_server.call/3
    (amqp 3.3.0) lib/amqp/connection.ex:258: AMQP.Connection.close/1
    (stdlib 5.2.2) gen_server.erl:1143: :gen_server.try_terminate/3
    (stdlib 5.2.2) gen_server.erl:1339: :gen_server.terminate/10
    (stdlib 5.2.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3402681644.1267204097.212382>, :process, #PID<0.5048.0>, :socket_closed_unexpectedly}
```

Maybe we can handle `{:DOWN, ....}` message?

Some links that found by this issue:
- https://elixirforum.com/t/trap-exits-to-ensure-linked-process-exits/48476/3
- https://elixirforum.com/t/how-to-correctly-handle-genserver-call-exits-because-of-non-existing-process/58284/9

**Comment by lucacorti** [comment]
The DOWN message handling is there, but I think a monitor on the connection process was missing. Can you try again with the new change?

**Comment by vermaxik** [comment]
Unfortunately, no luck, the same issue. I just want to highlight that I happened when the connection with RabbitMQ is lost (restarting the amqp service).

P.S. We have also kafka in the app, with restarting kafka service it also terminating with the similar exception.

**Comment by lucacorti** [comment]
Ahhhh, I see. I'm attempting to close the connection after the down but it's already gone. I've added a new commit that should avoid trying to close an already closed connection.

**Comment by vermaxik** [comment]
Amazing, now it works 🎉 👍 🚀  only see nice error and warning (as expected) and it recovered after backing off. 

```bash
[warning] Connection (#PID<0.1267.0>) closing: received hard error {:"connection.close", 320,
 "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'",
 0, 0} from server
[warning] Connection down, restarting...
[warning] Connection (#PID<0.1270.0>) closing: received hard error {:"connection.close", 320,
 "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'",
 0, 0} from server
[warning] Connection down, restarting...
[warning] Connection (#PID<0.1201.0>) closing: received hard error {:"connection.close", 320,
 "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'",
 0, 0} from server
[warning] Connection down, restarting...
[error] Connection error: :econnrefused for MyApp.Workers.Lapin.AMQPPublisherWorker, backing off for 1000
```

Thank you for the quick fix. When to expect release?
