### ISSUE TITLE
Improper support for wildcards in routing keys

### ISSUE THREAD

**Issue by bdusauso** [lucacorti/lapin#17]
It seems Lapin currently doesn't support wildcards in routing keys correctly.

# Environment
* Elixir 1.5.3
* Lapin 0.3.1

# Steps to reproduce bug
Given this configuration
```elixir
config :lapin, :connections, [
  [
    uri: "amqp://mq",
    module: MessagePublisher,
    channels: [
      [
        role: :producer,
        exchange: "events",
        exchange_type: :topic,
        queue: "lapin_test",
        queue_durable: true,
        publisher_persistent: true,
        routing_key: "*"
      ]
    ]
  ]
]
```

And publisher:
```elixir
defmodule MessagePublisher do
  use Lapin.Connection
end
```

Sending a message like this
```elixir
MessagePublisher.publish("events", "foo", %{bar: :baz} |> Poison.encode!)
```
results in an error message:

`{:error, "Error publishing message: no channel for exchange 'events' with routing key 'foo'"}`

# Result expected
Message publishing should have occurred without any problem as the routing key set when publishing message should have matched the wildcard used in the binding.

**Comment by lucacorti** [comment]
This is fixed in 0.3.2, allowing publishers on topic exchanges to publish regardless of the routing key. Thanks @bdusauso for the report and testing.
