### ISSUE TITLE
type heartbeaters() undefined

### ISSUE THREAD

**Issue by samirbilalmemon** [lucacorti/lapin#175]
I face compilation error type heartbeaters() undefined

I searched Lapin documentation and github issues for Lapin and could not find anything related to heartbeat

**Comment by lucacorti** [comment]
Can you please include the complete error you are getting from the compiler?

**Comment by samirbilalmemon** [comment]
iex -S mix
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:128:8] [ds:128:8:10] [async-threads:1] [jit:ns]

===> Analyzing applications...
===> Compiling rabbit_common
===> Compiling src/rabbit_heartbeat.erl failed
rabbit_heartbeat.erl:22:39: syntax error before: 'maybe'

rabbit_heartbeat.erl:20:2: type heartbeaters() undefined
rabbit_heartbeat.erl:32:13: type heartbeaters() undefined
rabbit_heartbeat.erl:38:13: type heartbeaters() undefined
rabbit_heartbeat.erl:49:21: type heartbeaters() undefined
rabbit_heartbeat.erl:50:22: type heartbeaters() undefined

** (Mix) Could not compile dependency :rabbit_common, "(mydirectory)/rebar3 bare compile --paths (mydirectory)/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile rabbit_common --force", update it with "mix deps.update rabbit_common" or clean it with "mix deps.clean rabbit_common"
