### ISSUE TITLE
Publishing 

### ISSUE THREAD

**Issue by lswith** [lucacorti/lapin#2]
Hey the publishing with this library seems a bit odd. 

In the config we specify which queue, exchange, and worker will be publishing but the publish function doesn't use any of this context.

An example config:
```elixir
config :lapin, :connections, [
  [
    handle: :myhandle,
    channels: [
      [
        role: :producer,
        worker: MyApp.SomeWorker,
        exchange: "some_exchange",
        queue: "some_queue"
      ]
    ]
  ]
]
```

An example of how a SomeWorker should not need to specify "exchange" or the "handle".
```elixir
defmodule MyApp.SomeWorker do
  use Lapin.Worker

  def publish do
    Worker.Publish("routing_key", %Lapin.Message{}, [])
  end
end
```

**Comment by lucacorti** [comment]
Hey Luke,

I'm not particularly happy that part of the API too. I'd like a solution which simplifies usage while also preserving the ability to automatically resolve the AMQP connection and channel.

The handle is currently needed for process registration and resolution, but could probably go away. 

Out of my mind, making `Lapin.Connection` a proper superset of `GenServer` and use the implementing module for connection process registration could make sense, but the `routing_key` would still be needed for channel resolution. 

Please bear with me as this work in progress right now, but this is something I intend to improve. If you have a specific proposal I'd love to discuss it.

Luca

**Comment by lucacorti** [comment]
Hey @lswith,

You can check out the `worker_refactor` branch with a proposed implementation of improved publishing and consuming:

- `Lapin.Worker` is gone. Callbacks are moved to `Lapin.Connection`, so there is a connection-wide worker module. To consume messages, one can directly pattern match on `%Message{meta: %{}}`.
- `Lapin.Pattern` is now a per-channel setting defaulting to reading the configuration file.
- A `publish` function is injected by the `use Lapin.Connection` in the worker module. This function still takes `exchange` and `routing_key`.

The documentation is updated as well describing the new apis and I'd like to know if this looks good to you.

**Comment by lswith** [comment]
I really like what you've done here for the publishing stuff. Such a nice API!

I'll trying using it soon and see how I go. 

One last question I have is whether it is possible to define a pattern in config as well? I like the idea of dynamic patterns but it would be nice to simply use the workqueue pattern directly from config.

**Comment by lucacorti** [comment]
Not sure I understand your issue. You can define patterns for each channel in the configuration with the `pattern` key. Can you elaborate? Maybe the docs are not clear about this?

**Comment by lswith** [comment]
ah whoops. I thought it was only configurable inside the worker.

**Comment by lucacorti** [comment]
Nice, I've been doing some more refatoring, including adding a Channel struct you can pattern match on when receiving message in the worker to distinguish where the messages are coming from since the worker module is now per connection.

Check out the docs in the worker_refactor branch. If you don't have major concerns I'm going to release this as 0.2.0 and move on to other stuff.

**Comment by lswith** [comment]
looks good!

**Comment by lucacorti** [comment]
Thanks, I've also imlemented payload encoding/decodnig to custom data types via a protocol.
This is merged into master too and I'm probably going to release it tomorrow. Check it out.
