### ISSUE TITLE
Documentation has lot of errors

### ISSUE THREAD

**Issue by AppyCat** [lucacorti/lapin#42]
Hi, the documentation has errors and typos whereby the code is not workable.

In config missing a comma, no end on some defs, etc.

Also it returns the following error:

Lapin.Worker is not loaded and could not be found

Am trying this in latest Elixir in Phoenix 1.4

**Comment by lucacorti** [comment]
Hi @AppyCat, I'm sorry you are experiencing trouble. Which version of Lapin are you running?

Also, feel free to open a PR to fix outstanding documentation issues or point them out so that I can fix those.
