### ISSUE TITLE
Properly support Publisher Confirms

### ISSUE THREAD

**Issue by lucacorti** [lucacorti/lapin#5]
Publisher confirms with `prefetch_count` > 1 need https://github.com/pma/amqp/issues/41 to be solved before they can be supported properly, another option could be to switch to `amqp_client`.

**Comment by bdusauso** [comment]
It seems latest AMQP version supports it: [release v1.2.0-rc.0](https://github.com/pma/amqp/releases/tag/v1.2.0-rc.0)

**Comment by lucacorti** [comment]
This is fixed in 0.4.0, thanks.
