### ISSUE TITLE
Problem with messages staying on the producer queue

### ISSUE THREAD

**Issue by michelboaventura** [lucacorti/lapin#56]
Hi,

I'm using Lapin as a producer only, with the following config:

```Elixir
config :lapin, :connections, [
  [
    module: TestLapin.Worker,
    channels: [
      [
        role: :producer,
        exchange: "my_exchange",
        exchange_type: :fanout,
        queue: "my_queue"
      ]
    ]
  ]
]
```

And `TestLapin.Worker` is just a dummy module:
```Elixir
defmodule TestLapin.Worker do
  use Lapin.Connection
end
```

I can see on my rabbit that a queue `my_queue` is created and bound with `my_exchange` and an empty routing key. I don't think Lapin should do this, because AFAIK we publish messages on rabbit straight to a exchange and don't need a queue for that. This causes the following problem:

If I publish a message without a routing key:
```Elixir
:ok = TestLapin.Worker.publish("my_exchange", "", "payload")
```
It is routed to `my_queue` and stays there forever, waiting to be consumed. If I use any routing key this doesn't happen because the queue is bound with an empty routing key.

So, I think Lapin should not create and bind a queue when configuring a producer.

Thanks.

**Comment by lucacorti** [comment]
Yes, that's a valid point, producers shouldn't declare queues at all. I've a large rewrite splitting consumers and producers in the works which would also address this, but haven't gotten around to finish it yet.

**Comment by michelboaventura** [comment]
Hi @lucacorti, I will wait then for your rewrite. Meanwhile I'm just making sure to always use a routing key. Besides this small issue I'm very happy with Lapin, it is working very nice in my projects, thank you for your work!

Cheers.

**Comment by lucacorti** [comment]
I'm glad you find it useful, I'll try to finish the consumer/producer split. Obviusly, PRs and issues are always welcome.

**Comment by lucacorti** [comment]
@michelboaventura I've done some work to get the rewrite in the `consumer_producer_pattern_flags` into shape. It should also address your issue.

I'm pretty confident it works, but I'd love some feedback from real world usage.

Docs are updated, and it should require minimal configuration changes. Could you try it out?

**Comment by michelboaventura** [comment]
Hi @lucacorti,

I'm trying the new code and it's looking great. I have two questions:

When creating a producer I can pass the exchange name alone which is great, but Lapin is not creating the exchange for me as it used to do. Is this by design?
Second, when creating a producer I've tried to create it with ``[exchange: "my_exchange", queue: "my_queue"]`` but it seems to not create the queue, because as soon as I start iex I get:

```erlang
21:22:27.817 [error] GenServer TestLapin.Worker terminating
** (stop) exited in: :gen_server.call(#PID<0.603.0>, {:subscribe, {:"basic.consume", 0, "my_queue", "", false, true, false, false, []}, #PID<0.605.0>}, 60000)
    ** (EXIT) shutdown: {:server_initiated_close, 404, "NOT_FOUND - no queue 'my_queue' in vhost '/'"}
    (stdlib 3.11.2) gen_server.erl:223: :gen_server.call/3
    (amqp 1.4.2) lib/amqp/basic.ex:351: AMQP.Basic.consume/4
    (lapin 0.4.0) lib/lapin/consumer.ex:96: Lapin.Consumer.create/2
    (elixir 1.10.2) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (lapin 0.4.0) lib/lapin/connection.ex:455: Lapin.Connection.create_consumers/2
    (lapin 0.4.0) lib/lapin/connection.ex:390: Lapin.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: %{configuration: [virtual_host: "/", port: 5672, host: 'localhost', uri: :pop, module: TestLapin.Worker, consumers: [[exchange: "my_exchange", queue: "my_queue"]]], connection: nil, consumers: [], module: nil, producers: []}

```

**Comment by lucacorti** [comment]
Yes, all declaration is now done in a separate configuration. You can find the details in `docs/main.md`.

**Comment by michelboaventura** [comment]
I should've read the full doc instead of parts of it :grimacing:. Everything seems to work fine now. I've migrate one of my systems to use this branch and will monitor it. I will ping you back in a couple of days. Thank you again!

**Comment by michelboaventura** [comment]
I've been using the new version for the last couple of days and everything is working flawless. Thank you very much for your fast fix @lucacorti.

Cheers!

**Comment by lucacorti** [comment]
Great! I did a master merge and will release that soon as 1.0 since there are breaking changes. Thank you so much for testing and your contribution!

**Comment by lucacorti** [comment]
@michelboaventura 1.0.0 is out now, thanks for your feedback, testing and PR.

**Comment by michelboaventura** [comment]
I've changed all my code to use it instead of pointing to Github and it's working greatly. Thanks!
