### ISSUE TITLE
Test consumers without RabbitMQ running

### ISSUE THREAD

**Issue by nTraum** [lucacorti/lapin#85]
Hi @lucacorti, first of all thanks for the library. Appreciate it a lot open-sourcing the library.

I am wondering how I can test consumer modules without having to run Rabbit MQ in my test environment.

Given I have a module like this one below, I'd like to verify the behavior when receiving the message with routing key `foo.bar`.

```elixir
defmodule MyProducer do
  use Lapin.Connection

  def handle_deliver(_channel, %Lapin.Message{
        meta: %{routing_key: "foo.bar"},
        payload: payload
      }) do
  # here be dragons
  end

  def handle_deliver(_channel, _message) do
    :ok
  end
end
```

Calling the function in a test context with a struct created manually for channel and message fails with an argument error.
Thanks in advance!

**Comment by lucacorti** [comment]
Hey @nTraum, thanks for the feedback, can you share how you are calling `MyProducer.handle_deliver/2` in your test?

**Comment by nTraum** [comment]
Well, I think this was a classic case of rubberduck-debugging! I just tried to reproduce it in a example repo for you and now it works!

For completeness sake, here is me just faking the message and channel as observable by inspecting a real one and using it for a test

```elixir
defmodule MyLapinTestTest.WorkerTest do
  use ExUnit.Case

  test "greets the world" do
    message = %Lapin.Message{meta: %{app_id: :undefined, cluster_id: :undefined, consumer_tag: "amq.ctag-NXAA7seVhNmaXiFYFIJz2A", content_encoding: :undefined, content_type: nil, correlation_id: :undefined, delivery_tag: 1, exchange: "some_exchange", expiration: :undefined, headers: [], message_id: :undefined, persistent: true, priority: :undefined, redelivered: false, reply_to: :undefined, routing_key: "test", timestamp: :undefined, type: :undefined, user_id: :undefined}, payload: "hi"}

    channel = %Lapin.Consumer{ channel: %AMQP.Channel{ conn: %AMQP.Connection{}, custom_consumer: {AMQP.SelectiveConsumer}}, config: [queue: "some_queue"], consumer_tag: "amq.ctag-NXAA7seVhNmaXiFYFIJz2A", pattern: Lapin.Consumer.Config, queue: "some_queue"}

    MyLapinTest.Worker.handle_deliver(channel, message)
  end
end
```

I'm not sure how much of it is actually needed, but I'll find out soon! Thanks anyway and sorry for bothering you unnecessarily! :fearful:

**Comment by lucacorti** [comment]
@nTraum aha, great! Let me know if you encounter any other issues.
