### ISSUE TITLE
Publisher/Consumer doesn't work

### ISSUE THREAD

**Issue by lswith** [lucacorti/lapin#9]
It seems if I wish to make a worker a publisher and a consumer it fails when trying to publish.

**Comment by lswith** [comment]
I think its this call to `Enum.find` https://github.com/lucacorti/lapin/blob/master/lib/lapin/channel.ex#L123. Find only returns the first which will probably always be the consumer.

**Comment by lucacorti** [comment]
That is a producer and a consumer channel configured on the same connection with the equal exchange/routing_key configuration. Good catch.
